name: sd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.4=py38h9ce1e76_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - future=0.18.2=py38_1
  - giflib=5.2.1=h5eee18b_1
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_1
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - openssl=1.1.1s=h7f8727e_0
  - pillow=9.3.0=py38hace64e9_1
  - pip=22.3.1=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_2
  - pyyaml=6.0=py38h5eee18b_1
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - accelerate==0.16.0
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==22.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - bleach==6.0.0
      - comm==0.1.2
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.12.1
      - executing==1.2.0
      - fastjsonschema==2.16.2
      - filelock==3.9.0
      - fqdn==1.5.1
      - huggingface-hub==0.12.0
      - importlib-metadata==6.0.0
      - importlib-resources==5.10.2
      - ipykernel==6.20.2
      - ipython==8.9.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.0.2
      - jupyter-console==6.4.4
      - jupyter-core==5.2.0
      - jupyter-events==0.6.3
      - jupyter-server==2.2.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - markupsafe==2.1.2
      - matplotlib-inline==0.1.6
      - mistune==2.0.4
      - mypy-extensions==0.4.3
      - nbclassic==0.5.1
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.7.3
      - nest-asyncio==1.5.6
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - opencv-python==4.7.0.68
      - packaging==23.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==2.6.2
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.36
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.14.0
      - pyrallis==0.3.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.4
      - pyzmq==25.0.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - regex==2022.10.31
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - safetensors==0.2.8
      - scipy==1.10.0
      - send2trash==1.8.0
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - stack-data==0.6.2
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tokenizers==0.13.2
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchvision==0.13.1+cu113
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.9.0
      - transformers==4.26.0
      - typing-inspect==0.8.0
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.0
      - widgetsnbextension==4.0.5
      - zipp==3.12.0
prefix: /home/evinpinar/miniconda3/envs/sd
